spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082