spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\Dev\ecom-microservice\configserver\src\main\resources\config

server:
  port: 8888
